= Lambdas

== About Java 8 Lambdas

Functional Interface Definition
____
A functional interface is any interface that contains only one abstract method.
(A functional interface may contain one or more default methods or static 
methods.) Because a functional 
interface contains only one abstract method, you can omit the name 
of that method when you implement it.
____

(`equals` is an explicit declaration of a concrete method 
 inherited from `Object` that, without this declaration, 
 would otherwise be implicitly declared.)

== Default Methods

* Enable you to add new functionality to the `interface` of your libraries
* Ensure binary compatibility with code written for older versions of those `interface`.
* Comes closer to have "concrete" method in an "interface" by composing other `abstract` methods.

.Default Method Arbitrary Example
[source%linenum, java, subs="verbatim,quotes", highlight=4..7]
----
public interface Human {
   public String getFirstName();
   public String getLastName();
   default public String getFullName() {
     return String.format("%s %s", 
        getFirstName(), getLastName());
   }
}
----

== Defining `MyPredicate`

* It's an interface
* One `abstract` method: `test`
* `default` methods don't count (More on that later)
* `static` methods don't count
* Any methods inherited from `Object` don't count either.

.src/main/java/com.xyzcorp.demos.functions.MyPredicate
[source, java, subs="verbatim, quotes"]
----
package com.xyzcorp;

public interface MyPredicate<T> {
   public boolean test(T item);
}
----

Conclusion: We can omit the name when we implement it.

== Functional `filter`

____
Filter is a higher-order function that processes a data structure (usually a list) in some order to produce a new data structure containing exactly those elements of the original data structure for which a given predicate returns the boolean value true.
____

https://en.wikipedia.org/wiki/Map_(higher-order_function)[Wikipedia: Map (higher-order function)]

=== Functional `filter` by example

* Given List of `list`:  `[1,2,3,4]`
* Given a function `f`:  `x -> x % 2 == 0`
* When calling `filter` on a `list` with `f`: `[1,2,3,4].filter(f)`
* Then a copy of the `list` should return: `[2,4]`

== Using `MyPredicate`

.src/main/java/com.xyzcorp.functions.Functions#myFilter
[source, java, subs="verbatim, quotes"]
----
public static <T> List<T> myFilter (List<T> list, MyPredicate<T> predicate) {
    ArrayList<T> result = new ArrayList<T>();
    for (T item : list) {
        if (predicate.test(item)) {
            result.add(item);
        }
    }
    return result;
}
----

NOTE: This is the functional `filter`

== Testing `MyPredicate`

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyFilter
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 
                                      19, 21, 33, 78, 93, 10);
List<Integer> filtered = Functions.myFilter(numbers,
   new MyPredicate<Integer>() {
       @Override
       public boolean test(Integer item) {
           return item % 2 == 0;
       }
   });
System.out.println(filtered);
----

NOTE: Here we are defining what the `Predicate` will do when sent into `filter`.

== Convert `MyPredicate` into a Lambda

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyFilter
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = 
   Arrays.asList(2, 4, 5, 1, 9, 15,
                 19, 21, 33, 78, 93, 10);
List<Integer> filtered = 
   Functions.myFilter(numbers, 
      item -> item % 2 == 0);
System.out.println(filtered);
----

== Defining `MyFunction`

.src/main/java/com.xyzcorp.demos.functions.MyFunction
[source, java, subs="attributes,quotes,verbatim"]
----
public interface MyFunction<T, R> {
    public R apply(T t);
}
----

== Functional `map`

____
Applies a given function to each element of a list, returning a list of results in the same order. It is often called apply-to-all when considered in functional form.
____
https://en.wikipedia.org/wiki/Map_(higher-order_function)[Wikipedia: Map (higher-order function)]


== Functional `map` by example

. Given List of `list`:  `[1,2,3,4]`
. Given a function `f`:  `x -> x + 1`
. When calling `map` on a `list` with `f`: `[1,2,3,4].map(f)`
. Then a copy of the `list` should return: `[2,3,4,5]`

== Using `MyFunction`

.src/main/java/com.xyzcorp.demos.functions.Functions#myMap
[source, java, subs="attributes,quotes,verbatim"]
----
public static <T, R> List<R> myMap(List<T> list, MyFunction<T, R> myFunction) {
    ArrayList<R> result = new ArrayList<>();
    for (T t : list) {
        result.add(myFunction.apply(t));
    }
    return result;
}
----

== Testing `MyFunction`

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyMap
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
                                      21, 33, 78, 93, 10);
List<Integer> mapped = Functions.myMap(numbers, 
  new MyFunction<Integer, Integer>() {
    @Override
    public Integer apply(Integer item) {
        return item + 2;
    }
});
System.out.println(mapped);
----

== Convert `MyFunction` into a Lambda

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyMap
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
List<Integer> mapped = Functions.myMap(numbers, t -> t + 2);
----

=== Functional `flatMap`

____
Applies a given function to each element of a list, returning a list of results 
in the same order. It is often called bind when considered in functional form.
____


== Functional `flatMap` by example

. Given List of `list`:  `[1,2,3,4]`
. Given a function `f`:  `x -> [x - 1, x, x + 1]`
. When calling `flatMap` on a `list` with `f`: `[1,2,3,4].flatMap(f)`
. Then a copy of the `list` should return: `[0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5]`

== Using `MyFunction` with `flatMap`

.src/main/java/com.xyzcorp.demos.functions.Functions#myFlatMap
[source, java, subs="attributes,quotes,verbatim"]
----
public static <T, R> List<R> myFlatMap(List<T> list, MyFunction<T, List<R>> myFunction) {
    ArrayList<R> result = new ArrayList<>();
    for (T t : list) {
        List<R> application = myFunction.apply(t);
        result.addAll(application);
    }
    return result;
}
----

== Testing `MyFunction` with `flatMap`

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyMap
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
List<Integer> mapped = Functions.myFlatMap(numbers,
    t -> List.of(t - 1, t, t + 1));
----

== Defining `MyConsumer`

.src/main/java/com.xyzcorp.demos.functions.MyConsumer.java
[source, java, subs="verbatim, quotes"]
----
package com.xyzcorp;

public interface MyConsumer<T> {
   public void accept(T item);
}
----

IMPORTANT: Notice that it does not return anything, a `void`

== Functional `forEach`
____
Performs an action on each element returning nothing or `void`, a sink
____

== Functional `forEach` by example

. Given List of `list`:  `[1,2,3,4]`
. Given a function `f`:  `x -> System.out.println(x)`
. When calling `forEach` on a `list` with `f`: `[1,2,3,4].forEach(f)`
. Then `void` is returned. This is called a side effect.

== Using `MyConsumer`

.src/main/java/com.xyzcorp.demos.functions.Functions#myForEach
[source, java, subs="attributes,quotes,verbatim"]
----
public static <T> void myForEach(List<T> list, MyConsumer<T> myConsumer) {
    for (T t : list) {
        myConsumer.accept(t);
    }
}
----

== Testing `MyConsumer`

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyForEach
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
Functions.myForEach(numbers, new MyConsumer<Integer>() {
    @Override
    public void accept(Integer x) {
        System.out.println(x);
    }
});
----

== Convert `MyConsumer` into a Lambda

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyForEach
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
Functions.myForEach(numbers, x -> System.out.println(x));
----

== A Detour with Method References

* When a lambda expression does nothing but call an existing method
* It's often clearer to refer to the existing method by name.
* Works with lambda expressions for methods that already have a name.

== Types of Method References

.Types of Method References
[cols="2*", options="header"]
|===
|Kind
|Example

|Reference to a static method
|`ContainingClass::staticMethodName`
|Reference to an instance method of a particular object
|`containingObject::instanceMethodName`
|Reference to an instance method of an arbitrary object of a particular type
|`ContainingType::methodName`
|Reference to a constructor 
|`ClassName::new`
|===

== `forEach` with a method reference

Before:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyForEach
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
Functions.myForEach(numbers, new MyConsumer<Integer>() {
    @Override
    public void accept(Integer x) {
        System.out.println(x);
    }
});
----

With a lambda:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyForEach
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
Functions.myForEach(numbers, x -> System.out.println(x));
----

After:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMyForEach
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(4, 5, 7, 8);
Functions.myForEach(numbers, System.out::println);
----

NOTE: Although confusing, in `System.out`, `out` is a `public final static` variable. Therefore, `println` is a non-static method of `java.io.PrintStream`. This is an instance method of an object.

== Static method with a method reference

Before:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAStaticMethod
[source, java, subs="verbatim, quotes"]
----
List<Integer> numbers = 
   Arrays.asList(2, 4, 5, 1, 9, 15, 19,
                 21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers, 
    new MyFunction<Integer, Integer>() {
       @Override
       public Integer apply(Integer a) {
           return Math.abs(a);
       }
}));
----

With a Lambda:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAStaticMethod
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = 
   Arrays.asList(2, 4, 5, 1, 9, 15, 19,
                 21, 33, 78, 93, 10);

System.out.println(Functions.myMap(numbers, a -> Math.abs(a)));
----

With a Method Reference:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAStaticMethod
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = 
   Arrays.asList(2, 4, 5, 1, 9, 15, 19,
                 21, 33, 78, 93, 10);

System.out.println(Functions.myMap(numbers, Math::abs));
----

=== Containing Type as a Method Reference

Before:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingType
[source, java, subs="verbatim, quotes"]
----
List<String> words = Arrays.asList("One", "Two", "Three", "Four");
List<Integer> result = Functions.myMap(words, new MyFunction<String,
    Integer>() {
    @Override
    public Integer apply(String s) {
        return s.length();
    }
});
System.out.println(result);
----

With a Lambda:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingType
[source, java, subs="attributes,quotes,verbatim"]
----
List<String> words = Arrays.asList("One", "Two", "Three", "Four");
List<Integer> result = Functions.myMap(words, s -> s.length());
System.out.println(result);
----

With a Method Reference:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingType
[source, java, subs="attributes,quotes,verbatim"]
----
List<String> words = Arrays.asList("One", "Two", "Three", "Four");
List<Integer> result = Functions.myMap(words, String::length);
System.out.println(result);
----

== Owner of the Method Reference

* The owner of the method might be any super type
* Not always the type that you are using

Before:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingTypeTrickQuestion
[source, java, subs="verbatim, quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers, new MyFunction<Integer,
    String>() {
    @Override
    public String apply(Integer integer) {
        return integer.toString();
    }
}));
----

With a Lambda:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingType
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers, integer -> integer.toString()));
----

With a Method Reference:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAContainingType
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers, Object::toString));
----

NOTE: Use your IDE to guide you. It's easier that way.

== Method Reference with an Instance

Given a custom TaxRate class:

.src/main/java/com.xyzcorp.demos.functions.TaxRate
[source, java, subs="verbatim,quotes"]
----
package com.xyzcorp;

public class TaxRate {
    private final int year;
    private final double taxRate;

    public TaxRate(int year, double taxRate) {
        this.year = year;
        this.taxRate = taxRate;
    }

    public double apply(int subtotal) {
        return (subtotal * taxRate) + subtotal;
    }

    //Getters, toString, equals elided
}
----

Before:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAnInstance
[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
TaxRate taxRate2016 = new TaxRate(2016, .085);
System.out.println(Functions.myMap(numbers, 
  new MyFunction<Integer, Double>() {
    @Override
    public Double apply(Integer subtotal) {
        return taxRate2016.apply(subtotal);
    }
}));
----

With a Lambda:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAnInstance
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
TaxRate taxRate2016 = new TaxRate(2016, .085);
System.out.println(Functions.myMap(numbers, subtotal -> taxRate2016.apply(subtotal)));
----

After:

.src/test/java/com.xyzcorp.demos.functions.FunctionsTest#testMethodReferenceAnInstance
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
        21, 33, 78, 93, 10);
TaxRate taxRate2016 = new TaxRate(2016, .085);
System.out.println(Functions.myMap(numbers, taxRate2016::apply));
----

NOTE: Use your IDE to guide you. It's easier that way.

===  Method Reference with an New Type

Before:

[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
    21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers,
    new MyFunction<Integer, Double>() {
        @Override
        public Double apply(Integer value) {
            return new Double(value);
        }
    }));
----

With A Lambda:

[source,java,subs="verbatim,quotes"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
            21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers,
    value -> new Double(value)));
----

After:
[source, java, subs="attributes,quotes,verbatim"]
----
List<Integer> numbers = Arrays.asList(2, 4, 5, 1, 9, 15, 19,
            21, 33, 78, 93, 10);
System.out.println(Functions.myMap(numbers, Double::new));
----

NOTE: Use your IDE to guide you. It's easier that way.

NOTE: `new Double` is deprecated in favor of `Double.valueOf(..)`. This was used for demonstration.

==  Create `MySupplier`

[source, java, subs="verbatim, quotes"]
----
package com.xyzcorp;

public interface MySupplier<T> {
   public T get();
}
----
NOTE: Compare the difference to `MyConsumer`

===  Create a `myGenerate` in *_Functions.java_*

[source, java]
----
public static <T> List<T> myGenerate(MySupplier<T> supplier, int count) {}
----

==  Use `myGenerate` in *_FunctionsTest.java_*

[source,java,linenums,subs="verbatim,quotes"]
----
package com.xyzcorp;

import org.junit.Test;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public class FunctionsTest {

    ...

    @Test
    public void testMyGenerate() {
        List<LocalDateTime> localDateTimes = 
          Functions.myGenerate(new MySupplier<LocalDateTime>() {
              @Override
              public LocalDateTime get() {
                  return LocalDateTime.now();
              }
          }, 10);
        System.out.println(localDateTimes);
    }
}
----
NOTE: `LocalDateTime.now()` is from the new Java Date/Time API from Java 8.

==  Viewing Consumer, Supplier, Predicate, Function, in the official Javadoc.

https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html


==  Multi-line Lambdas

[source, java, subs="verbatim,quotes"]
----
package com.xyzcorp;

import org.junit.Test;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public class FunctionsTest {

    ...

    @Test
    public void testLambdasWithRunnable() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                String threadName =
                        Thread.currentThread().getName();
                System.out.format("%s: %s%n",
                        threadName,
                        "Hello from another thread");
            }
        });
        t.start();
    }
}
----
NOTE: `Runnable` is an `interface` with one `abstract` method.

== Closure
* _Lexical scoping_ caches values provided in one context for use later in another context.
* If lambda expression closes over the scope of its definition, it is a _closure_.

[source, java, subs="verbatim,quotes"]
----
public static Integer foo
        (Function<Integer, Integer> f) {
    return f.apply(5);
}

public void otherMethod() {
    Integer x = 3;
    Function<Integer, Integer> add3 = z -> x + z;
    System.out.println(foo(add3));
}
----

== Lexical Scoping Restrictions
* To avoid any race conditions:
** The variable that is being in enclosed must either be:
*** `final`
*** _Effectively final_. No change can be made after used in a closure.

== Closure Error

The following will not work...

[source, java, subs="verbatim,quotes"]
----
public static Integer foo
        (Function<Integer, Integer> f) {
    return f.apply(5);
}

public void otherMethod() {
    Integer x = 3;
    Function<Integer, Integer> add3 = z -> x + z;
    x = 10;
    System.out.println(foo(add3));
}
----

==  Create Duplicated Code 

An application for a closure is to avoid repetition.

[source, java, subs="verbatim, quotes"]

----
package com.xyzcorp;

import org.junit.Test;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public class FunctionsTest {

    ...

    @Test
    public void testClosuresAvoidRepeats() {
        MyPredicate<String> stringHasSizeOf4 =
                str -> str.length() == 4;

        MyPredicate<String> stringHasSizeOf2 =
                str -> str.length() == 2;

        List<String> names = Arrays.asList("Foo", "Ramen", "Naan", "Ravioli");
        System.out.println(Functions.myFilter(names, stringHasSizeOf4));
        System.out.println(Functions.myFilter(names, stringHasSizeOf2));
    }
}
----


==  Refactor Duplicated Code with a Closure

An application for a closure is to avoid repetition.

[source, java, subs="verbatim, quotes"]
----
package com.xyzcorp;

import org.junit.Test;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public class FunctionsTest {

    ...

    public MyPredicate<String> stringHasSizeOf(final int length) {
        return null; //Create your closure here
    }

    @Test
    public void testClosuresAvoidRepeats() {
        List<String> names = Arrays.asList("Foo", "Ramen", "Naan", "Ravioli");
        System.out.println(Functions.myFilter(names, stringHasSizeOf(4)));
        System.out.println(Functions.myFilter(names, stringHasSizeOf(2)));
    }
}
----